name: CI Backend (Spring Boot)

on:
  push:
    branches: [ main ]
    paths:
      - 'controle-financeiro-backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'controle-financeiro-backend/**'

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./controle-financeiro-backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      # Mantendo o skipTests até ter a suíte de testes pronta
      run: ./mvnw clean package -DskipTests
